// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'libpixer_android_arm64.so': '7e506d41a39ec46715c55e02235e45b9',
  'libpixer_android_armv7.so': '3738717bbf6dcdbb85fdb2fa29d8cd42',
  'libpixer_android_x86_64.so': '91a8830198a2cf8c0328e10c2474060d',
  'libpixer_ios_arm64.dylib': 'ed2d357bc143d9e14fa384fd19561265',
  'libpixer_ios_sim_arm64.dylib': '01b1391c7fbbc80759a23f9411d8f609',
  'libpixer_ios_sim_x86_64.dylib': '6dffb30b88a06d896d9865804fdc0b85',
  'libpixer_linux_aarch64.so': 'fb5b10e371646aadedec7f770d98417c',
  'libpixer_linux_x86_64.so': '7f4d16379e7b4cddcb62fe5b1f553785',
  'libpixer_macos_arm64.dylib': '6889038894c0bfdcd185fa1524700b68',
  'libpixer_macos_x86_64.dylib': '086a5639f07ca4f8aa57e197ee0e742b',
  'pixer_windows_arm64.dll': '47f0f14dbf1056c450893f587b400571',
  'pixer_windows_x86_64.dll': '7bffbaf677b1ef63ac241ae21d272d59',
};
