// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// ABI contract version. Increment for incompatible signatures, layouts, or IDs.
@ffi.Native<ffi.Uint32 Function()>(isLeaf: true)
external int pixer_abi_version();

/// Pixel-buffer byte length for native memory accounting; zero for a null handle.
@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ImageHandle>)>(isLeaf: true)
external int pixer_image_byte_length(ffi.Pointer<ImageHandle> handle);

/// Free a buffer returned by `pixer_batch_encode`.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.UintPtr)>(
  isLeaf: true,
)
external void pixer_free_buffer(ffi.Pointer<ffi.Uint8> ptr, int len);

/// Free an image handle
@ffi.Native<ffi.Void Function(ffi.Pointer<ImageHandle>)>(isLeaf: true)
external void pixer_free(ffi.Pointer<ImageHandle> handle);

/// Load an image from a file path into `out_image`.
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ImageHandle>>,
  )
>()
external int pixer_load(
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Pointer<ImageHandle>> out_image,
);

/// Load an image from memory into `out_image`.
///
/// `format` is an `ImageFormatEnum` value, or `PIXER_FORMAT_DETECT`.
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<ImageHandle>>,
  )
>()
external int pixer_load_from_memory(
  ffi.Pointer<ffi.Uint8> data,
  int len,
  int format,
  ffi.Pointer<ffi.Pointer<ImageHandle>> out_image,
);

/// Get image metadata
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ImageHandle>,
    ffi.Pointer<ImageMetadata>,
  )
>(isLeaf: true)
external int pixer_get_metadata(
  ffi.Pointer<ImageHandle> handle,
  ffi.Pointer<ImageMetadata> out_metadata,
);

/// Apply a batch and write the final image to `out_image`. The source image
/// is unchanged.
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ImageHandle>,
    ffi.Pointer<PixerOperation>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Pointer<ImageHandle>>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external int pixer_batch_to_image(
  ffi.Pointer<ImageHandle> handle,
  ffi.Pointer<PixerOperation> operations,
  int operation_count,
  ffi.Pointer<ffi.Pointer<ImageHandle>> out_image,
  ffi.Pointer<ffi.UintPtr> out_failed_index,
);

/// Apply a batch and encode the final image. `format` is an `ImageFormatEnum`
/// value; `jpeg_quality` (1..=100) is read only for JPEG.
/// Caller must free the buffer using `pixer_free_buffer`.
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ImageHandle>,
    ffi.Pointer<PixerOperation>,
    ffi.UintPtr,
    ffi.Uint32,
    ffi.Uint8,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.UintPtr>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external int pixer_batch_encode(
  ffi.Pointer<ImageHandle> handle,
  ffi.Pointer<PixerOperation> operations,
  int operation_count,
  int format,
  int jpeg_quality,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_data,
  ffi.Pointer<ffi.UintPtr> out_len,
  ffi.Pointer<ffi.UintPtr> out_failed_index,
);

/// Apply a batch and save the final image to a file; the extension picks the format.
@ffi.Native<
  ImageErrorCode$1 Function(
    ffi.Pointer<ImageHandle>,
    ffi.Pointer<PixerOperation>,
    ffi.UintPtr,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.UintPtr>,
  )
>()
external int pixer_batch_save(
  ffi.Pointer<ImageHandle> handle,
  ffi.Pointer<PixerOperation> operations,
  int operation_count,
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.UintPtr> out_failed_index,
);

/// Sampling filter used when resizing.
///
/// Quality and cost roughly increase from top to bottom; `Lanczos3` is the
/// default and produces the sharpest results, `Nearest` is the fastest.
enum FilterTypeEnum {
  /// Nearest-neighbour. Fastest, blocky output. Good for pixel art.
  Nearest(0),

  /// Linear (a.k.a. bilinear). Cheap, slightly blurry.
  Triangle(1),

  /// Catmull-Rom cubic. Sharper than `Triangle`, can ring on edges.
  CatmullRom(2),

  /// Gaussian. Soft output, useful for downscaling without aliasing.
  Gaussian(3),

  /// Lanczos with `a = 3`. Highest quality, slowest. Default.
  Lanczos3(4);

  final int value;
  const FilterTypeEnum(this.value);

  static FilterTypeEnum fromValue(int value) => switch (value) {
    0 => Nearest,
    1 => Triangle,
    2 => CatmullRom,
    3 => Gaussian,
    4 => Lanczos3,
    _ => throw ArgumentError('Unknown value for FilterTypeEnum: $value'),
  };
}

typedef FilterTypeEnum$1 = ffi.Uint32;
typedef DartFilterTypeEnum = int;

/// Result of every fallible Pixer function; outputs are written through
/// out-parameters only on `Success`.
enum ImageErrorCode {
  /// The operation succeeded.
  Success(0),

  /// The provided path is empty, malformed, or refers to a non-existent file.
  InvalidPath(1),

  /// The image format is not recognised or not supported by this build.
  UnsupportedFormat(2),

  /// The image bytes are corrupt or do not match the expected format.
  DecodingError(3),

  /// Encoding the image to the requested format failed.
  EncodingError(4),

  /// An underlying I/O operation (read/write) failed.
  IoError(5),

  /// Width, height, or crop bounds are zero or exceed the image.
  InvalidDimensions(6),

  /// A handle or output pointer was null, or the image has been freed.
  InvalidPointer(7),

  /// A scalar parameter (e.g. JPEG quality, blur sigma) is out of range.
  InvalidParameter(8),

  /// An unclassified error occurred.
  Unknown(99);

  final int value;
  const ImageErrorCode(this.value);

  static ImageErrorCode fromValue(int value) => switch (value) {
    0 => Success,
    1 => InvalidPath,
    2 => UnsupportedFormat,
    3 => DecodingError,
    4 => EncodingError,
    5 => IoError,
    6 => InvalidDimensions,
    7 => InvalidPointer,
    8 => InvalidParameter,
    99 => Unknown,
    _ => throw ArgumentError('Unknown value for ImageErrorCode: $value'),
  };
}

typedef ImageErrorCode$1 = ffi.Uint32;
typedef DartImageErrorCode = int;

/// Image container format used for both decoding and encoding.
enum ImageFormatEnum {
  /// Portable Network Graphics — lossless, alpha supported.
  Png(0),

  /// JPEG — lossy, no alpha. Quality is configurable on encode.
  Jpeg(1),

  /// Graphics Interchange Format — palette-based, supports animation
  /// (single-frame only via this API).
  Gif(2),

  /// WebP — lossy or lossless, alpha supported.
  WebP(3),

  /// Windows Bitmap — uncompressed, large files.
  Bmp(4),

  /// Windows Icon — multi-resolution container.
  Ico(5),

  /// Tagged Image File Format — typically lossless.
  Tiff(6);

  final int value;
  const ImageFormatEnum(this.value);

  static ImageFormatEnum fromValue(int value) => switch (value) {
    0 => Png,
    1 => Jpeg,
    2 => Gif,
    3 => WebP,
    4 => Bmp,
    5 => Ico,
    6 => Tiff,
    _ => throw ArgumentError('Unknown value for ImageFormatEnum: $value'),
  };
}

typedef ImageFormatEnum$1 = ffi.Uint32;
typedef DartImageFormatEnum = int;

/// Stable operation identifiers shared by the native and Dart batch APIs.
///
/// Each variant documents how it reads the `PixerOperation` slots; unused
/// slots are ignored.
enum PixerOperationKind {
  /// Fit within `arg0` x `arg1`, preserving aspect ratio. `arg2`: `FilterTypeEnum`.
  Resize(0),

  /// Resize to exactly `arg0` x `arg1`. `arg2`: `FilterTypeEnum`.
  ResizeExact(1),

  /// `arg0`, `arg1`: origin; `arg2`, `arg3`: width and height.
  Crop(2),
  Rotate90(3),
  Rotate180(4),
  Rotate270(5),
  FlipHorizontal(6),
  FlipVertical(7),

  /// Gaussian blur, `scalar`: sigma (zero or a positive normal f32).
  Blur(8),

  /// `arg0`: i32 offset added to color channels, preserving alpha.
  Brightness(9),

  /// `scalar`: finite f32 contrast around the midpoint; 0 is neutral.
  Contrast(10),
  Grayscale(11),
  Invert(12);

  final int value;
  const PixerOperationKind(this.value);

  static PixerOperationKind fromValue(int value) => switch (value) {
    0 => Resize,
    1 => ResizeExact,
    2 => Crop,
    3 => Rotate90,
    4 => Rotate180,
    5 => Rotate270,
    6 => FlipHorizontal,
    7 => FlipVertical,
    8 => Blur,
    9 => Brightness,
    10 => Contrast,
    11 => Grayscale,
    12 => Invert,
    _ => throw ArgumentError('Unknown value for PixerOperationKind: $value'),
  };
}

typedef PixerOperationKind$1 = ffi.Uint32;
typedef DartPixerOperationKind = int;

final class ImageHandle extends ffi.Opaque {}

final class ImageMetadata extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint8()
  external int color_type;
}

/// One operation in a batch. Arguments are interpreted according to `kind`.
final class PixerOperation extends ffi.Struct {
  @ffi.Uint32()
  external int kind;

  @ffi.Int64()
  external int arg0;

  @ffi.Int64()
  external int arg1;

  @ffi.Int64()
  external int arg2;

  @ffi.Int64()
  external int arg3;

  @ffi.Double()
  external double scalar;
}

const int PIXER_FORMAT_DETECT = 4294967295;
