[package]
name = "pixer"
version = "0.1.0"
edition = "2024"

[lib]
name = "pixer"
crate-type = ["staticlib", "cdylib"]

[dependencies]
image = { version = "0.25.5", default-features = false }
fast_image_resize = "6.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fast_image_resize = { version = "6.1.0", features = ["rayon"] }

# Keep in sync with `supportedFormats` in packages/pixer/lib/src/hook/local_build.dart.
[features]
default = ["bmp", "gif", "ico", "jpeg", "png", "tiff", "webp"]
bmp = ["image/bmp"]
gif = ["image/gif"]
ico = ["image/ico"]
jpeg = ["image/jpeg"]
png = ["image/png"]
tiff = ["image/tiff"]
webp = ["image/webp"]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
